// Unit tests for the main-only `secretsAdmin` wrapper.
//
// References:
//   - tasks.md §3.2 (Extend the main-side secret-key allowlist)
//   - requirements.md §Requirement 15.1, 15.2, 15.3
//   - design.md §`secrets` (existing table, key allowlist extended)
//
// The wrapper accepts the three OpenClash keys plus any
// `cpaAuth.providerAuth.<uuid>` key, and rejects everything else.

import { describe, it, expect, beforeEach } from 'vitest';
import {
  createSecretsModule,
  type SecretsModule,
  type SecretsStore,
  type SafeStorageLike,
} from './secrets';
import { createSecretsAdmin } from './secrets.admin';

function buildSecrets(): SecretsModule {
  const map = new Map<string, Buffer>();
  const store: SecretsStore = {
    getEncrypted: (k) => map.get(k) ?? null,
    setEncrypted: (k, v) => {
      map.set(k, v);
    },
    deleteByKey: (k) => {
      map.delete(k);
    },
  };
  const safeStorage: SafeStorageLike = {
    isEncryptionAvailable: () => true,
    encryptString: (p) => Buffer.from(p, 'utf-8'),
    decryptString: (b) => b.toString('utf-8'),
  };
  return createSecretsModule({ store, safeStorage });
}

describe('secretsAdmin wrapper', () => {
  let secrets: SecretsModule;

  beforeEach(() => {
    secrets = buildSecrets();
  });

  describe('fixed allowlist (renderer-shared keys)', () => {
    it.each([
      'openclash.controllerSecret',
      'openclash.management.username',
      'openclash.management.password',
    ])('round-trips set/get/remove for fixed key %s', (key) => {
      const admin = createSecretsAdmin(secrets);
      admin.set(key, 'plaintext-value');
      expect(admin.get(key)).toBe('plaintext-value');
      admin.remove(key);
      expect(admin.get(key)).toBeNull();
    });
  });

  describe('Provider_Auth dynamic allowlist', () => {
    it('accepts a canonical lower-case UUIDv4 key', () => {
      const admin = createSecretsAdmin(secrets);
      const key = 'cpaAuth.providerAuth.0123abcd-4567-89ef-0123-456789abcdef';
      admin.set(key, '{"accessToken":"xxx"}');
      expect(admin.get(key)).toBe('{"accessToken":"xxx"}');
      admin.remove(key);
      expect(admin.get(key)).toBeNull();
    });

    it('accepts a UUID generated by crypto.randomUUID', () => {
      const admin = createSecretsAdmin(secrets);
      // crypto.randomUUID() always produces canonical lower-case v4.
      const id = crypto.randomUUID();
      const key = `cpaAuth.providerAuth.${id}`;
      admin.set(key, 'payload');
      expect(admin.get(key)).toBe('payload');
    });
  });

  describe('rejection paths', () => {
    const cases: ReadonlyArray<{ name: string; key: string }> = [
      { name: 'unknown literal', key: 'random.unrelated.key' },
      // Legacy renderer-managed key is NOT on the secretsAdmin allowlist;
      // it stays on the renderer-facing path per Q2 decision.
      { name: 'legacy deepseek key', key: 'deepseek_api_key' },
      // Wrong prefix.
      {
        name: 'wrong prefix',
        key: 'cpaAuth.other.0123abcd-4567-89ef-0123-456789abcdef',
      },
      // Too short / too long / non-hex chars.
      { name: 'too short uuid', key: 'cpaAuth.providerAuth.abc' },
      {
        name: 'uppercase hex (regex requires lower-case)',
        key: 'cpaAuth.providerAuth.0123ABCD-4567-89EF-0123-456789ABCDEF',
      },
      {
        name: 'non-hex character in uuid slot',
        key: 'cpaAuth.providerAuth.0123abcd-4567-89ef-0123-456789abcdez',
      },
      { name: 'empty string', key: '' },
    ];

    it.each(cases)('rejects $name on set', ({ key }) => {
      const admin = createSecretsAdmin(secrets);
      expect(() => admin.set(key, 'v')).toThrow(/secretsAdmin: unknown key/);
    });

    it.each(cases)('rejects $name on get', ({ key }) => {
      const admin = createSecretsAdmin(secrets);
      expect(() => admin.get(key)).toThrow(/secretsAdmin: unknown key/);
    });

    it.each(cases)('rejects $name on remove', ({ key }) => {
      const admin = createSecretsAdmin(secrets);
      expect(() => admin.remove(key)).toThrow(/secretsAdmin: unknown key/);
    });

    it('does not write to the underlying store on rejection', () => {
      const admin = createSecretsAdmin(secrets);
      expect(() => admin.set('forbidden', 'v')).toThrow();
      // Verify by going through the underlying secrets directly.
      expect(secrets.get('forbidden')).toBeNull();
    });

    it('error message echoes only the key name, not the value', () => {
      const admin = createSecretsAdmin(secrets);
      const sensitive = 'super-secret-token-do-not-leak';
      try {
        admin.set('forbidden.key', sensitive);
        expect.fail('expected throw');
      } catch (err) {
        expect(err).toBeInstanceOf(Error);
        const msg = (err as Error).message;
        expect(msg).toContain('forbidden.key');
        expect(msg).not.toContain(sensitive);
      }
    });
  });
});
